#spring.application.name=fullstack_development

spring:
  application:
    name: fullstack_development
  datasource:
    username: fahadkhan
    password: 123456
    url: jdbc:mysql://localhost:3306/fullstack_development
#    jdbc:mysql://database-1.cv0mmigaeapf.us-west-1.rds.amazonaws.com:3306/fullstack
#
    driver-class-name: com.mysql.cj.jdbc.Driver


  flyway:
    validate-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
cors:
  allowed-origins: "*"
  allowed-methods: "*"

  #    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect







#spring.security.user.name=fahadkhan
#spring.security.user.password=123456



